### ISSUE TITLE
Documentation part

### ISSUE THREAD

**Issue by anirudhramanan** [flipkart-incubator/batchman#25]

**Comment by thekirankumar** [comment]
The documentation should describe from a use case perspective rather than from the components perspective.

For example, instead of describing NetworkOnReadyListener, you can describe the use case like "Pushing a batch to network reliably"

Other topics can be "Preventing event loss", "Bounding disk queue size (trimming)", "Serialization using a different library", "Persist events on DB", "Using batchman to batch DB queries" etc

**Comment by kushalsharma** [comment]
Agree, I will improve the docs over the weekend.
